version: '3'
services:
  main:
    image: node:20
    working_dir: /app
    environment:
      - PORT=${PORT}
    volumes:
      - .:/app
    command: yarn start
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

# networks:
#   network1:
